language: python
python:
- '2.7'
- '3.3'
install:
- pip install codecov
- pip install coverage
script:
- python -m unittest discover -v ./ci_play/
- coverage run ./ci_play/test.py
after_success:
- codecov
addons:
  ssh_known_hosts: moon.scs.ryerson.ca
before_deploy:
- openssl aes-256-cbc -K $encrypted_36194199902e_key -iv $encrypted_36194199902e_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/src esinlao@moon.scs.ryerson.ca:/home/avm/courses/cps847/esinlao
  on:
    branch: master
